# GG Bot Upload Assistant
# Copyright (C) 2022  Noob Master669

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.

# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Docker compose for GG-Bot Auto Uploader
# please note that this compose file cannot be used with GG-Bot Upload Assistant
# ------------------------------------
# To use this compose file, you'll need to create the following file in the location where you have this compose file
# and provide values for the following variables (samples for all these files are available in the env-files-samples folder)
#
# .env file           -> variables for docker-compose
# .rutorrent.env      -> rutorrent related environment variables
# reupload.config.env -> gg-bot reuploader configurations
#
version: "3.5"
services:
  mongo:
    image: mongo:${MONGO_VERSION}
    hostname: mongo
    restart: unless-stopped
    volumes:
      - ${BASE_PATH}/apps/mongo:/data/db
  mongo-express:
    image: mongo-express:${MONGO_EXPRESS_VERSION}
    env_file:
      - .mongo_express.env
    depends_on:
      - mongo
    ports:
      - ${MONGO_EXPRESS_EXPOSE_PORT}:8081
  rutorrent:
    image: romancin/rutorrent:${RUTORRENT_VERSION}
    hostname: rutorrent
    restart: unless-stopped
    env_file:
      - .rutorrent.env
    volumes:
      - ${BASE_PATH}/apps/rutorrent/config:/config
      - ${BASE_PATH}/data/downloads:/downloads
      # uncomment below line to bring your own htpasswd file
      # see dev_scripts to see how to create this .htpasswd file yourself
      #- ${BASE_PATH}/.htpasswd:/config/nginx/.htpasswd
    ports:
      - ${RUTORRENT_WEBUI_PORT}:80
      - ${RUTORRENT_EXTRA_PORTS}:51415-51415
  gg-bot-auto-uploader:
    image: noobmaster669/gg-bot-uploader:${GG_BOT_REUPLOADER_VERSION}
    restart: unless-stopped
    hostname: gg-bot-reuploader
    # change the below volume mapping according to your torrent client
    volumes:
      - ${BASE_PATH}/data/downloads:/downloads
    env_file:
      - reupload.config.env
    ports:
      - ${VISOR_SERVER_PORT}:30035
    # based on your configuration the gg-bot-auto-uploader will depend on either mongo or redis
    # if using mongo comment out redis, and vice-versa
    depends_on:
      - mongo
      - rutorrent
    # provide the list of trackers to upload to here
    # TODO see how this can be taken from the .env file
    command: [ "-t", "<TRACKERS>", "<OPTIONAL_ARGUMENTS>" ]
